name: Quality Checks

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ["main"]

env:
  TITLE: "${{ github.event.pull_request.title || github.event.head_commit.message }}"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Version Check
        uses: EndBug/version-check@v2.1.0
      - name: Build
        run: touch build.txt
      - name: Output Title
        run: echo $TITLE

  static-tests:
    name: "Static Tests"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Lint
        run: cat build.txt

  unit-tests:
    name: "Unit Tests"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Unit Tests
        run: echo "Unit Tests Pass!"

  e2e-test:
    name: "End to End Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: End to End Tests
        run: echo "End to End Tests Pass!"
